# -*- coding: utf-8 -*-
"""Herencia_Ejercicio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h1GTNX7wf5xeQunJ_J5V6vUQwuy_kIf7
"""

class Trabajadores:
      nombre: str
      bono: int
      def __init__(self,nombre):
        self.nombre= nombre
      def bonus(self):
        print("No posee bonos")
      
      
class bonus(Trabajadores):
    def __init__(self,nombre):
      if profesion=="Secretaria":
         print("Su bono es de " + (ant1*1000))
      elif profesion=="Programador":
           print("Su bono es de " + (ant2*1000))


class Secretaria(bonus):
    salS=15000
    def __init__(self, nombre):
      nuevo_nombre= nombre + " Secretaria"
      super().__init__(nuevo_nombre)
    def salario(self):
        print (self.nombre + "Su salario es de $" + salS)
  
class Programador(bonus):
    salP=25000
    def __init__(self, nombre):
       nuevo_nombre= nombre + " Programador"
       super().__init__(nuevo_nombre)
    def salario(self):
        print (self.nombre + "Su salario es de $ " + salP)

class Gerente(Trabajadores):
    salG=50000
    def __init__(self, nombre):
       nuevo_nombre= nombre + "Gerente"
       super().__init__(nuevo_nombre)
    def salario(self):
        print (self.nombre + "Su salario es de $" + salG)

lista= (("Isabel", "Secretaria", 5),
        ("Carlos", "Programador", 3),
        ("Emanuel", "Gerente", 10))
prof= []
ant1:int
ant2:int
ant3:int

for nombre,profesion,antiguedad in lista:
  if profesion == "Secretaria":
     prof.append(Secretaria(nombre))
     ant1= antiguedad
  elif profesion == "Programador":
       prof.append(Programador(nombre))
       ant2= antiguedad
  elif profesion == "Gerente":
       prof.append(Gerente(nombre))
       ant3= antiguedad

for Trabajadores in prof:
  Trabajadores.bonus()

print("Usted es el gerente, desea aumentar el salario a un trabajador?(Si/No")
input (res)
res: char
res1: char
salN: int
if res=="Si":
   print("A quien le va ha aumentar el salario?(S/P)")
   input (res1)
   if res1=="S":
     print("Escriba el aumento")
     input (salN)
     salS+=salN
   elif res1=="P":
     print("Escriba el aumento")
     input (salN)
     salP+=salN
elif res=="No":
     print ("Gracias")